In [1]:
import numpy as np
from numpy import loadtxt
import matplotlib as plt
import scipy as sp
import pandas as pd
%matplotlib inline

In [2]:
DMDataArray = np.load('ctrees_1.npy') # Calls in data from .dat file.
DMDataArray.shape # Finds shape of array of data.

(9789948, 56)

np.save('ctrees_1',DMDataArray) # Saves data as a binary file for quicker read times.

In [3]:
DMTitles=['scale(0)', 'id(1)', 'desc_scale(2)', 'desc_id(3)', 'num_prog(4)', 'pid(5)', 'upid(6)', 'desc_pid(7)',
          'phantom(8)','sam_mvir(9)', 'mvir(10)', 'rvir(11)', 'rs(12)', 'vrms(13)', 'mmp?(14)', 'scale_of_last_MM(15)',
          'vmax(16)', 'x(17)','y(18)', 'z(19)', 'vx(20)', 'vy(21)', 'vz(22)', 'Jx(23)', 'Jy(24)', 'Jz(25)', 'Spin(26)',
          'Breadth_first_ID(27)','Depth_first_ID(28)', 'Tree_root_ID(29)', 'Orig_halo_ID(30)', 'Snap_num(31)', 
          'Next_coprogenitor_depthfirst_ID(32)','Last_progenitor_depthfirst_ID(33)', 'Rs_Klypin', 'Mvir_all',
          'M200b', 'M200c', 'M500c', 'M2500c', 'Xoff','Voff','Spin_Bullock', 'b_to_a', 'c_to_a', 'A[x]', 'A[y]', 
          'A[z]', 'b_to_a(500c)', 'c_to_a(500c)', 'A[x](500c)','A[y](500c)','A[z](500c)', 'T/|U|', 'M_pe_Behroozi', 
          'M_pe_Diemer'] # List of titles for columns.

In [4]:
DMDataTitled = pd.DataFrame(data=DMDataArray,columns=DMTitles)
DMDataTitled # Adds titles to columns and arranges array into fancy table (DataFrame).

scale(0)       id(1)  desc_scale(2)  desc_id(3)  num_prog(4)  \
0          0.1450  12755624.0         0.0000        -1.0        177.0   
1          0.1443  12491054.0         0.1450  12755624.0        164.0   
2          0.1443  12491055.0         0.1450  12755624.0          1.0   
3          0.1443  12491056.0         0.1450  12755624.0          1.0   
4          0.1443  12491060.0         0.1450  12755624.0          1.0   
5          0.1443  12491061.0         0.1450  12755624.0          1.0   
6          0.1443  12491062.0         0.1450  12755624.0          1.0   
7          0.1443  12491063.0         0.1450  12755624.0          1.0   
8          0.1443  12491064.0         0.1450  12755624.0          1.0   
9          0.1443  12491065.0         0.1450  12755624.0          1.0   
10         0.1443  12491066.0         0.1450  12755624.0          1.0   
11         0.1443  12491067.0         0.1450  12755624.0          1.0   
12         0.1443  12491068.0         0.1450  12755624.0          1.0   
13         0.1443  12491070.0         0.1450  12755624.0          1.0   
14         0.1443  12491071.0         0.1450  12755624.0          1.0   
15         0.1443  12491072.0         0.1450  12755624.0          1.0   
16         0.1443  12491073.0         0.1450  12755624.0          1.0   
17         0.1443  12491074.0         0.1450  12755624.0          1.0   
18         0.1443  12491075.0         0.1450  12755624.0          1.0   
19         0.1443  12491078.0         0.1450  12755624.0          1.0   
20         0.1443  12491079.0         0.1450  12755624.0          1.0   
21         0.1443  12491081.0         0.1450  12755624.0          1.0   
22         0.1443  12491082.0         0.1450  12755624.0          1.0   
23         0.1443  12491083.0         0.1450  12755624.0          1.0   
24         0.1443  12491084.0         0.1450  12755624.0          1.0   
25         0.1443  12491085.0         0.1450  12755624.0          1.0   
26         0.1443  12491086.0         0.1450  12755624.0          1.0   
27         0.1443  12491087.0         0.1450  12755624.0          1.0   
28         0.1443  12491088.0         0.1450  12755624.0          1.0   
29         0.1443  12491089.0         0.1450  12755624.0          1.0   
...           ...         ...            ...         ...          ...   
9789918    0.1450  12906864.0         0.0000        -1.0          1.0   
9789919    0.1443  12651788.0         0.1450  12906864.0          1.0   
9789920    0.1420  12365620.0         0.1443  12651788.0          0.0   
9789921    0.1450  12906868.0         0.0000        -1.0          1.0   
9789922    0.1443  12651792.0         0.1450  12906868.0          1.0   
9789923    0.1420  12365624.0         0.1443  12651792.0          0.0   
9789924    0.1450  12906973.0         0.0000        -1.0          1.0   
9789925    0.1443  12651897.0         0.1450  12906973.0          1.0   
9789926    0.1420  12365717.0         0.1443  12651897.0          1.0   
9789927    0.1396  12066773.0         0.1420  12365717.0          1.0   
9789928    0.1374  11771204.0         0.1396  12066773.0          1.0   
9789929    0.1351  11477434.0         0.1374  11771204.0          1.0   
9789930    0.1329  11185360.0         0.1351  11477434.0          0.0   
9789931    0.1450  12907003.0         0.0000        -1.0          1.0   
9789932    0.1443  12651928.0         0.1450  12907003.0          1.0   
9789933    0.1420  12365741.0         0.1443  12651928.0          1.0   
9789934    0.1396  12066791.0         0.1420  12365741.0          0.0   
9789935    0.1450  12907022.0         0.0000        -1.0          1.0   
9789936    0.1443  12651947.0         0.1450  12907022.0          1.0   
9789937    0.1420  12365758.0         0.1443  12651947.0          1.0   
9789938    0.1396  12066802.0         0.1420  12365758.0          0.0   
9789939    0.1450  12907059.0         0.0000        -1.0          1.0   
9789940    0.1443  12651984.0         0.1450  12907059.0          1

In [5]:
DMDataTitled.shape

(9789948, 56)

In [6]:
uniqueScales = DMDataTitled['scale(0)'].unique()

In [7]:
print sorted(uniqueScales)

[0.0292, 0.029700000000000001, 0.030200000000000001, 0.030700000000000002, 0.031199999999999999, 0.031699999999999999, 0.032300000000000002, 0.032800000000000003, 0.033300000000000003, 0.0339, 0.034500000000000003, 0.035000000000000003, 0.0356, 0.036200000000000003, 0.036799999999999999, 0.037400000000000003, 0.037999999999999999, 0.038699999999999998, 0.039300000000000002, 0.040000000000000001, 0.040599999999999997, 0.041300000000000003, 0.042000000000000003, 0.042700000000000002, 0.043400000000000001, 0.0441, 0.0448, 0.045600000000000002, 0.046300000000000001, 0.047100000000000003, 0.047899999999999998, 0.0487, 0.049500000000000002, 0.050299999999999997, 0.051200000000000002, 0.051999999999999998, 0.052900000000000003, 0.053800000000000001, 0.054600000000000003, 0.055500000000000001, 0.056500000000000002, 0.0574, 0.058400000000000001, 0.059299999999999999, 0.060299999999999999, 0.0613, 0.062300000000000001, 0.063399999999999998, 0.064399999999999999, 0.065500000000000003, 0.066600000

In [8]:
scaleFactors = DMDataTitled['scale(0)']
print scaleFactors

0          0.1450
1          0.1443
2          0.1443
3          0.1443
4          0.1443
5          0.1443
6          0.1443
7          0.1443
8          0.1443
9          0.1443
10         0.1443
11         0.1443
12         0.1443
13         0.1443
14         0.1443
15         0.1443
16         0.1443
17         0.1443
18         0.1443
19         0.1443
20         0.1443
21         0.1443
22         0.1443
23         0.1443
24         0.1443
25         0.1443
26         0.1443
27         0.1443
28         0.1443
29         0.1443
            ...  
9789918    0.1450
9789919    0.1443
9789920    0.1420
9789921    0.1450
9789922    0.1443
9789923    0.1420
9789924    0.1450
9789925    0.1443
9789926    0.1420
9789927    0.1396
9789928    0.1374
9789929    0.1351
9789930    0.1329
9789931    0.1450
9789932    0.1443
9789933    0.1420
9789934    0.1396
9789935    0.1450
9789936    0.1443
9789937    0.1420
9789938    0.1396
9789939    0.1450
9789940    0.1443
9789941    0.1420
9789942   

In [9]:
redshifts = (1/scaleFactors)-1

In [10]:
print redshifts

0          5.896552
1          5.930007
2          5.930007
3          5.930007
4          5.930007
5          5.930007
6          5.930007
7          5.930007
8          5.930007
9          5.930007
10         5.930007
11         5.930007
12         5.930007
13         5.930007
14         5.930007
15         5.930007
16         5.930007
17         5.930007
18         5.930007
19         5.930007
20         5.930007
21         5.930007
22         5.930007
23         5.930007
24         5.930007
25         5.930007
26         5.930007
27         5.930007
28         5.930007
29         5.930007
             ...   
9789918    5.896552
9789919    5.930007
9789920    6.042254
9789921    5.896552
9789922    5.930007
9789923    6.042254
9789924    5.896552
9789925    5.930007
9789926    6.042254
9789927    6.163324
9789928    6.278020
9789929    6.401925
9789930    6.524454
9789931    5.896552
9789932    5.930007
9789933    6.042254
9789934    6.163324
9789935    5.896552
9789936    5.930007


In [11]:
DMDataTitled.insert(56,'redshift',redshifts)
print DMDataTitled

         scale(0)       id(1)  desc_scale(2)  desc_id(3)  num_prog(4)  \
0          0.1450  12755624.0         0.0000        -1.0        177.0   
1          0.1443  12491054.0         0.1450  12755624.0        164.0   
2          0.1443  12491055.0         0.1450  12755624.0          1.0   
3          0.1443  12491056.0         0.1450  12755624.0          1.0   
4          0.1443  12491060.0         0.1450  12755624.0          1.0   
5          0.1443  12491061.0         0.1450  12755624.0          1.0   
6          0.1443  12491062.0         0.1450  12755624.0          1.0   
7          0.1443  12491063.0         0.1450  12755624.0          1.0   
8          0.1443  12491064.0         0.1450  12755624.0          1.0   
9          0.1443  12491065.0         0.1450  12755624.0          1.0   
10         0.1443  12491066.0         0.1450  12755624.0          1.0   
11         0.1443  12491067.0         0.1450  12755624.0          1.0   
12         0.1443  12491068.0         0.1450  12755

In [12]:
def massCrit(z,LWI):
    return ((2.5*10**5)*((1+z)/26)**(-3/2))*(1+6.96(4*np.pi*LWI))

def massA(z):
    return (5.4*10**7)*(((1+z)/11)**(-3/2)) # use whichever is smaller

In [13]:
redshifts = DMDataTitled['redshift'].values
print redshifts

[ 5.89655172  5.93000693  5.93000693 ...,  5.89655172  5.93000693
  6.04225352]


flatRedshifts = redshifts.flatten()
print flatRedshifts

In [14]:
np.unique(redshifts)

array([  5.89655172,   5.93000693,   6.04225352,   6.16332378,
         6.27802038,   6.4019245 ,   6.52445448,   6.65110941,
         6.77604977,   6.90513834,   7.03858521,   7.16993464,
         7.30564784,   7.43881857,   7.58369099,   7.72600349,
         7.87311446,   8.01713255,   8.16590284,   8.31966449,
         8.46969697,   8.63391137,   8.79431929,   8.95024876,
         9.12145749,   9.28806584,   9.46025105,   9.62699256,
         9.81081081,   9.98901099,  10.17318436,  10.3507378 ,
        10.54734411,  10.7370892 ,  10.93317422,  11.12121212,
        11.33045623,  11.53132832,  11.7388535 ,  11.95336788,
        12.17523057,  12.38688086,  12.60544218,  12.83125864,
        13.06469761,  13.30615165,  13.53488372,  13.77104874,
        14.01501502,  14.26717557,  14.52795031,  14.77287066,
        15.05136437,  15.3132137 ,  15.58374793,  15.86340641,
        16.12328767,  16.42160279,  16.69911504,  17.01801802,
        17.31501832,  17.58736059,  17.90359168,  18.23

In [15]:
# Using dotted green curve for LW feedback. Using that curve to interpolate LW feedback at each redshift.
# Working under the assumption that the feedback flatlines at redshifts less than 10.

In [16]:
def JLW21(z):
    if (z <= 10):
        return 7
    elif ((z > 10) & (z <= 15)):
        return (-1*z)+17
    elif ((z > 15) & (z <= 20)):
        return (-0.32*z)+6.8
    elif ((z > 20) & (z <= 25)):
        return (-0.07*z)+1.8
    elif ((z > 25) & (z <= 30)):
        return (-0.0093*z)+0.2825
    elif ((z > 30) & (z <= 35)):
        return (-0.00069*z)+0.0242

JLW21(redshifts)

In [17]:
redshifts.shape

(9789948,)

In [18]:
LWIntensity = []

for z in redshifts:
    LWIntensity.append(JLW21(z))
LWIntensity = pd.DataFrame(data=LWIntensity)

LWIntensity = JLW21(redshifts)

In [19]:
print LWIntensity

           0
0        7.0
1        7.0
2        7.0
3        7.0
4        7.0
5        7.0
6        7.0
7        7.0
8        7.0
9        7.0
10       7.0
11       7.0
12       7.0
13       7.0
14       7.0
15       7.0
16       7.0
17       7.0
18       7.0
19       7.0
20       7.0
21       7.0
22       7.0
23       7.0
24       7.0
25       7.0
26       7.0
27       7.0
28       7.0
29       7.0
...      ...
9789918  7.0
9789919  7.0
9789920  7.0
9789921  7.0
9789922  7.0
9789923  7.0
9789924  7.0
9789925  7.0
9789926  7.0
9789927  7.0
9789928  7.0
9789929  7.0
9789930  7.0
9789931  7.0
9789932  7.0
9789933  7.0
9789934  7.0
9789935  7.0
9789936  7.0
9789937  7.0
9789938  7.0
9789939  7.0
9789940  7.0
9789941  7.0
9789942  7.0
9789943  7.0
9789944  7.0
9789945  7.0
9789946  7.0
9789947  7.0

[9789948 rows x 1 columns]


In [20]:
DMDataTitled.insert(57,'LW Intensity',LWIntensity)
print DMDataTitled

         scale(0)       id(1)  desc_scale(2)  desc_id(3)  num_prog(4)  \
0          0.1450  12755624.0         0.0000        -1.0        177.0   
1          0.1443  12491054.0         0.1450  12755624.0        164.0   
2          0.1443  12491055.0         0.1450  12755624.0          1.0   
3          0.1443  12491056.0         0.1450  12755624.0          1.0   
4          0.1443  12491060.0         0.1450  12755624.0          1.0   
5          0.1443  12491061.0         0.1450  12755624.0          1.0   
6          0.1443  12491062.0         0.1450  12755624.0          1.0   
7          0.1443  12491063.0         0.1450  12755624.0          1.0   
8          0.1443  12491064.0         0.1450  12755624.0          1.0   
9          0.1443  12491065.0         0.1450  12755624.0          1.0   
10         0.1443  12491066.0         0.1450  12755624.0          1.0   
11         0.1443  12491067.0         0.1450  12755624.0          1.0   
12         0.1443  12491068.0         0.1450  12755

In [32]:
DMDataTitled = DMDataTitled.reset_index(drop=True, inplace=True)
print DMDataTitled

AttributeError: 'function' object has no attribute 'reset_index'

In [21]:
DMDataTitled = DMDataTitled[DMDataTitled['upid(6)'] == -1.0]
print DMDataTitled

         scale(0)       id(1)  desc_scale(2)  desc_id(3)  num_prog(4)  pid(5)  \
0          0.1450  12755624.0         0.0000        -1.0        177.0    -1.0   
1          0.1443  12491054.0         0.1450  12755624.0        164.0    -1.0   
2          0.1443  12491055.0         0.1450  12755624.0          1.0    -1.0   
7          0.1443  12491063.0         0.1450  12755624.0          1.0    -1.0   
8          0.1443  12491064.0         0.1450  12755624.0          1.0    -1.0   
10         0.1443  12491066.0         0.1450  12755624.0          1.0    -1.0   
14         0.1443  12491071.0         0.1450  12755624.0          1.0    -1.0   
15         0.1443  12491072.0         0.1450  12755624.0          1.0    -1.0   
19         0.1443  12491078.0         0.1450  12755624.0          1.0    -1.0   
24         0.1443  12491084.0         0.1450  12755624.0          1.0    -1.0   
25         0.1443  12491085.0         0.1450  12755624.0          1.0    -1.0   
27         0.1443  12491087.

In [22]:
DMDataValues = DMDataTitled.values
print DMDataValues

[[  1.45000000e-01   1.27556240e+07   0.00000000e+00 ...,   4.97600000e+09
    5.89655172e+00   7.00000000e+00]
 [  1.44300000e-01   1.24910540e+07   1.45000000e-01 ...,   4.80600000e+09
    5.93000693e+00   7.00000000e+00]
 [  1.44300000e-01   1.24910550e+07   1.45000000e-01 ...,   6.50200000e+05
    5.93000693e+00   7.00000000e+00]
 ..., 
 [  1.45000000e-01   1.29071360e+07   0.00000000e+00 ...,   0.00000000e+00
    5.89655172e+00   7.00000000e+00]
 [  1.44300000e-01   1.26520610e+07   1.45000000e-01 ...,   0.00000000e+00
    5.93000693e+00   7.00000000e+00]
 [  1.42000000e-01   1.23658570e+07   1.44300000e-01 ...,   0.00000000e+00
    6.04225352e+00   7.00000000e+00]]


In [23]:
DMDataTitled = DMDataTitled.sort_values(by = 'scale(0)', ascending = True)
print DMDataTitled

         scale(0)       id(1)  desc_scale(2)  desc_id(3)  num_prog(4)  pid(5)  \
1112349    0.0292        36.0         0.0297       149.0          0.0    -1.0   
3388326    0.0292         1.0         0.0297        96.0          0.0    -1.0   
1151882    0.0292        34.0         0.0297       146.0          0.0    -1.0   
244187     0.0292        39.0         0.0297       153.0          0.0    -1.0   
363533     0.0292        12.0         0.0297       119.0          0.0    -1.0   
295071     0.0292        35.0         0.0297       147.0          0.0    -1.0   
244191     0.0292        44.0         0.0297       158.0          0.0    -1.0   
406698     0.0292        17.0         0.0297       124.0          0.0    -1.0   
715337     0.0292        19.0         0.0297       126.0          0.0    -1.0   
125494     0.0292        21.0         0.0297       129.0          0.0    -1.0   
821421     0.0292         9.0         0.0297       114.0          0.0    -1.0   
244188     0.0292        40.

In [24]:
DMExtras = DMDataTitled[['mvir(10)','redshift','LW Intensity']]
print DMExtras

             mvir(10)   redshift  LW Intensity
1112349  3.224000e+04  33.246575       0.00126
3388326  8.060000e+04  33.246575       0.00126
1151882  3.762000e+04  33.246575       0.00126
244187   1.612000e+04  33.246575       0.00126
363533   2.687000e+04  33.246575       0.00126
295071   2.687000e+04  33.246575       0.00126
244191   5.911000e+04  33.246575       0.00126
406698   5.911000e+04  33.246575       0.00126
715337   9.673000e+04  33.246575       0.00126
125494   9.135000e+04  33.246575       0.00126
821421   8.598000e+04  33.246575       0.00126
244188   2.687000e+04  33.246575       0.00126
244190   2.687000e+04  33.246575       0.00126
354212   8.598000e+04  33.246575       0.00126
244189   2.257000e+05  33.246575       0.00126
363532   1.451000e+05  33.246575       0.00126
3388327  2.687000e+04  33.246575       0.00126
1445470  2.150000e+04  33.246575       0.00126
3388328  1.343000e+05  33.246575       0.00126
244186   1.720000e+05  33.246575       0.00126
210215   3.76

In [25]:
DMExtraValues = DMDataTitled[['mvir(10)','redshift','LW Intensity']].values
print DMExtraValues

[[  3.22400000e+04   3.32465753e+01   1.25986301e-03]
 [  8.06000000e+04   3.32465753e+01   1.25986301e-03]
 [  3.76200000e+04   3.32465753e+01   1.25986301e-03]
 ..., 
 [  1.77300000e+05   5.89655172e+00   7.00000000e+00]
 [  1.77300000e+05   5.89655172e+00   7.00000000e+00]
 [  6.43600000e+09   5.89655172e+00   7.00000000e+00]]


In [26]:
# mark as pristine (1) or not (0)
# if mass is greater than criitcal mass, change label from (1) to (0)
# at next step, check if all predecessors are pristine (1) or not (0). If pristine, do as above. Otherwise, skip.
# for now, galaxies above the critical mass will be assigned a single 100 solar mass star

In [ ]:
for mass, z, LWI in DMExtraValues:
    if 